In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.8026e-45, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 1.4013e-45]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9454, 0.6899, 0.5848],
        [0.1965, 0.4866, 0.5494],
        [0.8777, 0.1853, 0.5261],
        [0.8490, 0.3916, 0.2456],
        [0.9147, 0.1088, 0.1056]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0164,  0.6084, -0.4508],
        [-1.2553, -0.2950,  0.5021],
        [ 0.5895, -0.0038,  0.8061],
        [-0.1465,  1.3516, -0.4050],
        [-0.0809, -2.6150, -0.9401]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0570,  1.3756, -0.1704],
        [-1.2347,  0.4210,  0.6073],
        [ 1.1903,  0.3047,  0.9876],
        [ 0.6578,  2.3128, -0.3526],
        [-0.0374, -2.2207, -0.8626]])


In [9]:
print(torch.add(x, y))

tensor([[ 0.0570,  1.3756, -0.1704],
        [-1.2347,  0.4210,  0.6073],
        [ 1.1903,  0.3047,  0.9876],
        [ 0.6578,  2.3128, -0.3526],
        [-0.0374, -2.2207, -0.8626]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0570,  1.3756, -0.1704],
        [-1.2347,  0.4210,  0.6073],
        [ 1.1903,  0.3047,  0.9876],
        [ 0.6578,  2.3128, -0.3526],
        [-0.0374, -2.2207, -0.8626]])


In [11]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 0.0570,  1.3756, -0.1704],
        [-1.2347,  0.4210,  0.6073],
        [ 1.1903,  0.3047,  0.9876],
        [ 0.6578,  2.3128, -0.3526],
        [-0.0374, -2.2207, -0.8626]])


In [12]:
print(x[:, 1])

tensor([ 0.6084, -0.2950, -0.0038,  1.3516, -2.6150])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.6660])
-2.666025400161743


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!